title: "Gymshark Analytics"
description: "An치lisis de flujo de datos con PySpark y blog acad칠mico sobre anal칤tica de streaming"
author: "Juan Camilo Rodr칤guez"
theme: minima
url: "https://neajuank.github.io"
baseurl: "/Actividad-Jekill-y-Spark"

markdown: kramdown

# Plugins recomendados
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Configuraci칩n del tema
minima:
  skin: classic
  social_links:
    github: NeaJuank
    linkedin: juancamilorodriguez
    email: juankiudc@gmail.com

# 游댢 Configuraci칩n personalizada de URLs
# Esto hace que los posts salgan como /posts/a침o-mes-dia-titulo/
permalink: /posts/:year-:month-:day-:title/

# Archivos y carpetas a excluir del build
exclude:
  - venv/
  - .venv/
  - README.md
  - "*.py"
  - "*.csv"
  - "*.ipynb"
