title: "Gymshark Analytics"
description: "Análisis de flujo de datos con PySpark y blog académico sobre analítica de streaming"
author: "Juan Camilo Rodríguez"
theme: minima
baseurl: "/Actividad-Jekill-y-Spark"
url: "https://neajuank.github.io"

# Permite mostrar publicaciones del directorio _posts
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Personalización del tema
minima:
  skin: classic
  social_links:
    github: NeaJuank
    linkedin: juancamilorodriguez
    email: juankiudc@gmail.com

# Configuración del build
exclude:
  - venv/
  - .venv/
  - README.md
  - "*.py"
  - "*.csv"
