title: "Gymshark Analytics"
description: "Análisis de flujo de datos con PySpark y blog académico sobre analítica de streaming"
author: "Juan Camilo Rodríguez"
theme: minima
url: "https://neajuank.github.io"
baseurl: "/Actividad-Jekill-y-Spark"

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: classic
  social_links:
    github: NeaJuank
    linkedin: juancamilorodriguez
    email: juankiudc@gmail.com

exclude:
  - venv/
  - .venv/
  - README.md
  - "*.py"
  - "*.csv"
